name: errors_warnings_study
description: Errors and warnings research tools
version: 0.0.1
#author: Luke Church <luke@church.name>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

#dev_dependencies:
#  test: ^0.12.0
